apiVersion: batch/v1
kind: CronJob
metadata:
  name: mdai-generate-logs
  namespace: synthetics
  labels:
    app.kubernetes.io/name: mdai-generate-logs
    app.kubernetes.io/part-of: mdai-log-generator
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: mdai-generate-logs
            app.kubernetes.io/part-of: mdai-log-generator
        spec:
          restartPolicy: Never
          containers:
            - name: base-info-service0-teamc
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "100m"
                requests:
                  memory: "32Mi"
                  cpu: "25m"
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DURATION
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: DURATION
                - name: RATE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: BASE_RATE
                - name: LOG_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: COMMON_LOG_MESSAGE
              args:
                - logs
                - --otlp-insecure
                - --otlp-endpoint=$(HOST_IP):4317
                - --duration=$(DURATION)
                - --rate=$(RATE)
                - --service=service0
                - '--otlp-attributes=service.name="service0"'
                - --severity-text=INFO
                - --severity-number=9
                - --body=$(LOG_MESSAGE)
                - '--telemetry-attributes=team="teamC"'
                - '--telemetry-attributes=region="us-east-1"'
                - '--telemetry-attributes=generator="telemetrygen"'
                - '--telemetry-attributes=traffic_profile="base"'

            - name: base-warning-service17-teamq
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "100m"
                requests:
                  memory: "32Mi"
                  cpu: "25m"
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DURATION
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: DURATION
                - name: RATE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: BASE_RATE
                - name: LOG_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: COMMON_LOG_MESSAGE
              args:
                - logs
                - --otlp-insecure
                - --otlp-endpoint=$(HOST_IP):4317
                - --duration=$(DURATION)
                - --rate=$(RATE)
                - --service=service17
                - '--otlp-attributes=service.name="service17"'
                - --severity-text=WARNING
                - --severity-number=13
                - --body=$(LOG_MESSAGE)
                - '--telemetry-attributes=team="teamQ"'
                - '--telemetry-attributes=region="us-east-1"'
                - '--telemetry-attributes=generator="telemetrygen"'
                - '--telemetry-attributes=traffic_profile="base"'

            - name: base-error-service42-teamz
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "100m"
                requests:
                  memory: "32Mi"
                  cpu: "25m"
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DURATION
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: DURATION
                - name: RATE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: BASE_RATE
                - name: LOG_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: COMMON_LOG_MESSAGE
              args:
                - logs
                - --otlp-insecure
                - --otlp-endpoint=$(HOST_IP):4317
                - --duration=$(DURATION)
                - --rate=$(RATE)
                - --service=service42
                - '--otlp-attributes=service.name="service42"'
                - --severity-text=ERROR
                - --severity-number=17
                - --body=$(LOG_MESSAGE)
                - '--telemetry-attributes=team="teamZ"'
                - '--telemetry-attributes=region="us-east-1"'
                - '--telemetry-attributes=generator="telemetrygen"'
                - '--telemetry-attributes=traffic_profile="base"'

            - name: noisy-service1234-teama
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "150m"
                requests:
                  memory: "32Mi"
                  cpu: "50m"
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DURATION
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: DURATION
                - name: RATE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: NOISY_RATE
                - name: LOG_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: COMMON_LOG_MESSAGE
              args:
                - logs
                - --otlp-insecure
                - --otlp-endpoint=$(HOST_IP):4317
                - --duration=$(DURATION)
                - --rate=$(RATE)
                - --service=service1234
                - '--otlp-attributes=service.name="service1234"'
                - --severity-text=INFO
                - --severity-number=9
                - --body=$(LOG_MESSAGE)
                - '--telemetry-attributes=team="teamA"'
                - '--telemetry-attributes=region="us-east-1"'
                - '--telemetry-attributes=generator="telemetrygen"'
                - '--telemetry-attributes=traffic_profile="noisy"'

            - name: xnoisy-service4321-teamb
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "64Mi"
                  cpu: "250m"
                requests:
                  memory: "32Mi"
                  cpu: "75m"
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: DURATION
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: DURATION
                - name: RATE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: XNOISY_RATE
                - name: LOG_MESSAGE
                  valueFrom:
                    configMapKeyRef:
                      name: mdai-telemetrygen-settings
                      key: COMMON_LOG_MESSAGE
              args:
                - logs
                - --otlp-insecure
                - --otlp-endpoint=$(HOST_IP):4317
                - --duration=$(DURATION)
                - --rate=$(RATE)
                - --service=service4321
                - '--otlp-attributes=service.name="service4321"'
                - --severity-text=INFO
                - --severity-number=9
                - --body=$(LOG_MESSAGE)
                - '--telemetry-attributes=team="teamB"'
                - '--telemetry-attributes=region="us-east-1"'
                - '--telemetry-attributes=generator="telemetrygen"'
                - '--telemetry-attributes=traffic_profile="xnoisy"'
