apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MyDecisive/octant-argo-example.git
    targetRevision: sp/octant-tests
    path: argocd/apps/
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
