apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MyDecisive/octant-argo-example.git
    targetRevision: rlaw/install-log-crd
    path: argocd/apps/
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
