apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdai
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: ghcr.io/mydecisive/charts
    chart: mdai-hub
    targetRevision: 0.9.3-envoy
    helm:
      valueFiles:
      - $values/argocd/mdai/chart/local-values.yaml
  - repoURL: https://github.com/MyDecisive/octant-argo-example.git
    targetRevision: main
    ref: values
  destination:
    name: "in-cluster"
    namespace: mdai
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 2
