apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: https://github.com/MyDecisive/octant-ui.git
    targetRevision: feat/octant-app
  - repoURL: ghcr.io/mydecisive/charts/octant
    chart: octant
    targetRevision: 0.1.0
  destination:
    name: "in-cluster"
    namespace: octant
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 2
