apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: /ghcr.io/mydecisive/charts
    chart: octant-ui
    targetRevision: 0.1.4
    helm:
      valueFiles:
        - $values/argocd/octant/values.yaml
  - repoURL: ghcr.io/mydecisive/charts
    chart: octant
    targetRevision: 0.1.0
  - repoURL: https://github.com/MyDecisive/octant-argo-example.git
    targetRevision: feat/octant-app
    ref: values
  destination:
    name: "in-cluster"
    namespace: octant
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 2
