apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: oci://ghcr.io/mydecisive/charts/octant-ui
    chart: octant-ui
    targetRevision: 0.1.3
    helm:
      parameters:
        - name: deployment.gateway_host
          value: http://mdai-gateway.mdai.svc.cluster.local:8081
  destination:
    name: "in-cluster"
    namespace: octant
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 2
